// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxdlGb3ZT2E96BHHoA489kgpW-TWsht1c',
    appId: '1:913437887294:web:29cf6ca8256582050dfa6f',
    messagingSenderId: '913437887294',
    projectId: 'voicetales-a9418',
    authDomain: 'voicetales-a9418.firebaseapp.com',
    storageBucket: 'voicetales-a9418.firebasestorage.app',
    measurementId: 'G-95B17XL8DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Gjcq51Em8fESTlLOeR0q-4ghea08i08',
    appId: '1:913437887294:android:f29a878f49ed3fab0dfa6f',
    messagingSenderId: '913437887294',
    projectId: 'voicetales-a9418',
    storageBucket: 'voicetales-a9418.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_MRbvYJESDUQfbadfGQ1zTU7mdr3N4AE',
    appId: '1:913437887294:ios:3f8821f04506e5da0dfa6f',
    messagingSenderId: '913437887294',
    projectId: 'voicetales-a9418',
    storageBucket: 'voicetales-a9418.firebasestorage.app',
    iosBundleId: 'com.example.voicetales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_MRbvYJESDUQfbadfGQ1zTU7mdr3N4AE',
    appId: '1:913437887294:ios:3f8821f04506e5da0dfa6f',
    messagingSenderId: '913437887294',
    projectId: 'voicetales-a9418',
    storageBucket: 'voicetales-a9418.firebasestorage.app',
    iosBundleId: 'com.example.voicetales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxdlGb3ZT2E96BHHoA489kgpW-TWsht1c',
    appId: '1:913437887294:web:3ffabc712bc8d3270dfa6f',
    messagingSenderId: '913437887294',
    projectId: 'voicetales-a9418',
    authDomain: 'voicetales-a9418.firebaseapp.com',
    storageBucket: 'voicetales-a9418.firebasestorage.app',
    measurementId: 'G-65SDF9R3MZ',
  );
}
