// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzQnRsT65CYwgyCicxQcHIbxSQ68AdBMw',
    appId: '1:539935166814:web:0836616ffcd59a2de1bfcf',
    messagingSenderId: '539935166814',
    projectId: 'feelog-997bc',
    authDomain: 'feelog-997bc.firebaseapp.com',
    storageBucket: 'feelog-997bc.firebasestorage.app',
    measurementId: 'G-2325WDHYL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdML5A2Gvi8u-nQUosE13wAuILDwL6oe0',
    appId: '1:539935166814:android:5f2c1630137bc12fe1bfcf',
    messagingSenderId: '539935166814',
    projectId: 'feelog-997bc',
    storageBucket: 'feelog-997bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt3hqu-REuMq3hujFAKWI4I59RjdBU-6Q',
    appId: '1:539935166814:ios:597f497c02131b18e1bfcf',
    messagingSenderId: '539935166814',
    projectId: 'feelog-997bc',
    storageBucket: 'feelog-997bc.firebasestorage.app',
    iosBundleId: 'com.example.voicetales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt3hqu-REuMq3hujFAKWI4I59RjdBU-6Q',
    appId: '1:539935166814:ios:550b24e5f07d8eeae1bfcf',
    messagingSenderId: '539935166814',
    projectId: 'feelog-997bc',
    storageBucket: 'feelog-997bc.firebasestorage.app',
    iosBundleId: 'com.example.feelogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzQnRsT65CYwgyCicxQcHIbxSQ68AdBMw',
    appId: '1:539935166814:web:3b4af2c3b7df53aae1bfcf',
    messagingSenderId: '539935166814',
    projectId: 'feelog-997bc',
    authDomain: 'feelog-997bc.firebaseapp.com',
    storageBucket: 'feelog-997bc.firebasestorage.app',
    measurementId: 'G-H21MQTCLBN',
  );

}